In [1]:
# spam_env\Scripts\Activate
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report

In [2]:
spam_classifier_data = pd.read_csv('D:/Text_classifier/Spam classifier/data/spam.csv',encoding='latin1')

In [3]:
spam_classifier_data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
spam_classifier_data=spam_classifier_data.drop(spam_classifier_data.columns[2:5],axis=1)

In [5]:
spam_classifier_data.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
spam_classifier_data=spam_classifier_data.dropna(axis=0)

In [7]:
spam_classifier_data.tail()

        v1                                                 v2
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [8]:
spam_classifier_data=spam_classifier_data.drop_duplicates()

In [9]:
spam_classifier_data.tail()

        v1                                                 v2
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [10]:
spam_classifier_data['v1'].value_counts()

v1
ham     4516
spam     653
Name: count, dtype: int64

In [11]:
spam_classifier_data.shape

(5169, 2)

In [12]:
spam_classifier_data['v2']=spam_classifier_data['v2'].str.strip()
spam_classifier_data['v2'] = spam_classifier_data['v2'].str.replace(r'\s+', ' ', regex=True)
spam_classifier_data['v2']=spam_classifier_data['v2'].str.lower()
spam_classifier_data['v2'] = spam_classifier_data['v2'].str.replace(r'[^a-zA-Z0-9.,!? ]', '', regex=True)

In [13]:
spam_classifier_data.head(100)

      v1                                                 v2
0    ham  go until jurong point, crazy.. available only ...
1    ham                      ok lar... joking wif u oni...
2   spam  free entry in 2 a wkly comp to win fa cup fina...
3    ham  u dun say so early hor... u c already then say...
4    ham  nah i dont think he goes to usf, he lives arou...
..   ...                                                ...
95  spam  your free ringtone is waiting to be collected....
96   ham                  watching telugu movie..wat abt u?
97   ham  i see. when we finish we have loads of loans t...
98   ham  hi. wk been ok  on hols now! yes on for a bit ...
99   ham  please dont text me anymore. i have nothing el...

[100 rows x 2 columns]

In [14]:
spam_classifier_data.tail()

        v1                                                 v2
5567  spam  this is the 2nd time we have tried 2 contact u...
5568   ham                will  b going to esplanade fr home?
5569   ham  pity,  was in mood for that. so...any other su...
5570   ham  the guy did some bitching but i acted like id ...
5571   ham                         rofl. its true to its name

In [15]:
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(spam_classifier_data['v2'])
Y=spam_classifier_data['v1']

In [16]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 67413 stored elements and shape (5169, 8958)>
  Coords	Values
  (0, 3680)	0.14718355171806355
  (0, 8304)	0.22805449061103691
  (0, 4505)	0.3248392913131446
  (0, 6131)	0.2534749735141129
  (0, 2437)	0.25094472862636574
  (0, 1378)	0.2463544949432578
  (0, 5744)	0.15821847747238052
  (0, 4239)	0.10826602360731703
  (0, 1836)	0.27399832550699255
  (0, 3767)	0.1813697415335564
  (0, 8777)	0.23077232672427547
  (0, 4644)	0.27399832550699255
  (0, 1834)	0.3099692620646218
  (0, 2153)	0.27399832550699255
  (0, 7905)	0.16126793446485485
  (0, 3728)	0.15212195894620323
  (0, 1136)	0.3248392913131446
  (0, 8542)	0.18442767904511614
  (1, 5709)	0.2767319100209511
  (1, 4680)	0.406925248497845
  (1, 4474)	0.5233434480300876
  (1, 8676)	0.4304438402468376
  (1, 5738)	0.5464988818914979
  (2, 4239)	0.07701690844250475
  (2, 3475)	0.11093720239678657
  :	:
  (5167, 4177)	0.22645107686338733
  (5167, 4783)	0.1550438812384136
  (5167, 7280)	0.17982912856031447
  (5167, 3425)	0.11849937379127992
  (5167, 4375)	0.12513137542606476
  (5167, 7885)	0.10022503890101231
  (5167, 1512)	0.1386131390452543
  (5167, 8592)	0.18796771253687325
  (5167, 5520)	0.20244207480960394
  (5167, 2707)	0.18118256130783214
  (5167, 8341)	0.20496611300342416
  (5167, 1863)	0.13292345360558094
  (5167, 7291)	0.19839923394779307
  (5167, 3007)	0.2356380484460796
  (5167, 3596)	0.26619108506912004
  (5167, 1871)	0.2736591049779578
  (5167, 4316)	0.2736591049779578
  (5167, 3822)	0.23715725117318245
  (5167, 961)	0.31454428965812303
  (5167, 1625)	0.3296337948433081
  (5168, 8019)	0.15223246189289844
  (5168, 4384)	0.5386377328230546
  (5168, 5435)	0.4057106995049369
  (5168, 8148)	0.45030874653025815
  (5168, 6725)	0.5650801106310762

In [17]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.1, stratify=Y, random_state=1)

In [18]:
print(X.shape,X_train.shape,X_test.shape)

(5169, 8958) (4652, 8958) (517, 8958)

In [19]:
model=MultinomialNB()

In [20]:
model.fit(X_train,Y_train)

MultinomialNB()

In [21]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

print("Accuracy on training data:",training_data_accuracy)

Accuracy on training data: 0.9641014617368874

In [22]:
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

print("Accuracy on testing data:",test_data_accuracy)

Accuracy on testing data: 0.9574468085106383

In [23]:

print(classification_report(Y_test, X_test_prediction))

              precision    recall  f1-score   support

         ham       0.95      1.00      0.98       452
        spam       1.00      0.66      0.80        65

    accuracy                           0.96       517
   macro avg       0.98      0.83      0.89       517
weighted avg       0.96      0.96      0.95       517